version: '3'
services:
  app:
    image: test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - "POSTGRES_DB=test"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"
    ports:
      - "5432:5432"